-   id: prettier
    name: prettier
    entry: prettier --write --list-different --ignore-unknown --no-error-on-unmatched-pattern
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["prettier@2.4.1"]
